export interface Player {
  name: string;
  tag: string;
  icon?: string;
  level: number;
  sdRank: string;
  sdRankImage?: string;
  fRank: string;
  fRankImage?: string;
  champion: string;
  championImage?: string;
  avgKda: number;
  avgCs: number;
}

export const players: Player[] = [
  {
    name: "beerman562",
    tag: "NA1",
    icon: "https://static.bigbrain.gg/assets/lol/riot_static/14.24.1/img/profileicon/1439.png",
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: "https://cdn3.emoji.gg/emojis/2370-lol-border9-challenger.png",
    fRank: "Challenger",
    fRankImage: "https://cdn3.emoji.gg/emojis/2370-lol-border9-challenger.png",
    champion: "Warwick",
    championImage:
      "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Warwick_0.jpg",
    avgKda: 3.25,
    avgCs: 7.0,
  },
  {
    name: "ShadowHunter",
    tag: "NA1",
    icon: undefined,
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: undefined,
    fRank: "Challenger",
    fRankImage: undefined,
    champion: "Rumble",
    championImage: undefined,
    avgKda: 4.54,
    avgCs: 5.6,
  },
  {
    name: "DragonSlayer",
    tag: "NA1",
    icon: undefined,
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: undefined,
    fRank: "Challenger",
    fRankImage: undefined,
    champion: "Zed",
    championImage: undefined,
    avgKda: 1.74,
    avgCs: 7.1,
  },
  {
    name: "Warrior123",
    tag: "NA1",
    icon: undefined,
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: undefined,
    fRank: "Challenger",
    fRankImage: undefined,
    champion: "Vayne",
    championImage: undefined,
    avgKda: 3.89,
    avgCs: 7.4,
  },
  {
    name: "MysticMage",
    tag: "NA1",
    icon: undefined,
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: undefined,
    fRank: "Challenger",
    fRankImage: undefined,
    champion: "Soraka",
    championImage: undefined,
    avgKda: 1.3,
    avgCs: 6.7,
  },
  {
    name: "SilentAssassin",
    tag: "NA1",
    icon: undefined,
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: undefined,
    fRank: "Challenger",
    fRankImage: undefined,
    champion: "Wukong",
    championImage: undefined,
    avgKda: 3.45,
    avgCs: 6.9,
  },
  {
    name: "FrostyFox",
    tag: "NA1",
    icon: undefined,
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: undefined,
    fRank: "Challenger",
    fRankImage: undefined,
    champion: "Jayce",
    championImage: undefined,
    avgKda: 1.45,
    avgCs: 6.7,
  },
  {
    name: "LightningBolt",
    tag: "NA1",
    icon: undefined,
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: undefined,
    fRank: "Challenger",
    fRankImage: undefined,
    champion: "Yasuo",
    championImage: undefined,
    avgKda: 3.63,
    avgCs: 4.7,
  },
  {
    name: "IronClad",
    tag: "NA1",
    icon: undefined,
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: undefined,
    fRank: "Challenger",
    fRankImage: undefined,
    champion: "Xayah",
    championImage: undefined,
    avgKda: 4.45,
    avgCs: 5.9,
  },
  {
    name: "StormCaller",
    tag: "NA1",
    icon: undefined,
    level: 1000,
    sdRank: "Challenger",
    sdRankImage: undefined,
    fRank: "Challenger",
    fRankImage: undefined,
    champion: "Rakan",
    championImage: undefined,
    avgKda: 4.73,
    avgCs: 6.6,
  },
];
